// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuakeReport.Data;

#nullable disable

namespace QuakeReport.Data.Migrations
{
    [DbContext(typeof(QuakeReportDbContext))]
    [Migration("20260811052612_AddBloodDonationCenters")]
    partial class AddBloodDonationCenters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuakeReport.Data.Models.AbuseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("MissingPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MissingPersonId", "CreatedAt");

                    b.ToTable("AbuseReports");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.BloodDonationCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("BloodTypes")
                        .HasColumnType("integer");

                    b.Property<int>("CenterType")
                        .HasColumnType("integer");

                    b.Property<int>("Components")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<Guid>("EarthquakeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ManagementCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeratedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NeedsSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OperatingInstructions")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<int>("OperationalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PublicEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PublicPhone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PublicWhatsApp")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SearchText")
                        .HasMaxLength(2200)
                        .HasColumnType("character varying(2200)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagementCodeHash")
                        .IsUnique();

                    b.HasIndex("SearchText");

                    b.HasIndex("EarthquakeId", "BloodTypes", "Components");

                    b.HasIndex("EarthquakeId", "OperationalStatus", "UpdatedAt");

                    b.HasIndex("EarthquakeId", "ModerationStatus", "OperationalStatus", "CenterType", "CreatedAt");

                    b.ToTable("BloodDonationCenters");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.BloodDonationCenterAbuseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BloodDonationCenterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BloodDonationCenterId", "CreatedAt");

                    b.ToTable("BloodDonationCenterAbuseReports");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.BloodDonationCenterComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BloodDonationCenterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BloodDonationCenterId", "CreatedAt");

                    b.ToTable("BloodDonationCenterComments");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.CollectionPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ContactWhatsApp")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<Guid>("EarthquakeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ManagementCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeratedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NeedsSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OperationalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReceivingInstructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SearchText")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagementCodeHash")
                        .IsUnique();

                    b.HasIndex("SearchText");

                    b.HasIndex("EarthquakeId", "OperationalStatus", "UpdatedAt");

                    b.HasIndex("EarthquakeId", "ModerationStatus", "OperationalStatus", "CreatedAt");

                    b.ToTable("CollectionPoints");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.CollectionPointAbuseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionPointId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionPointId", "CreatedAt");

                    b.ToTable("CollectionPointAbuseReports");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.CollectionPointComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionPointId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionPointId", "CreatedAt");

                    b.ToTable("CollectionPointComments");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.DamageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DamageSigns")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EarthquakeId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int?>("StructureSize")
                        .HasColumnType("integer");

                    b.Property<int?>("StructureType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EarthquakeId");

                    b.HasIndex("CreatedAt", "Id");

                    b.HasIndex("Severity", "CreatedAt", "Id");

                    b.ToTable("DamageReports");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.Earthquake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EpicenterLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("EpicenterLongitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Magnitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Earthquakes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EpicenterLatitude = 4.5709,
                            EpicenterLongitude = -74.297300000000007,
                            IsActive = true,
                            Magnitude = 7.4000000000000004,
                            Name = "M7.4 - Colombia",
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("QuakeReport.Data.Models.HelpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EarthquakeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ManagementCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeratedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("NeedCategories")
                        .HasColumnType("integer");

                    b.Property<string>("NeedDetails")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTimeOffset?>("NeededBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("PublicEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PublicPhone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PublicWhatsApp")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SearchText")
                        .HasMaxLength(1800)
                        .HasColumnType("character varying(1800)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagementCodeHash")
                        .IsUnique();

                    b.HasIndex("SearchText");

                    b.HasIndex("EarthquakeId", "Status", "UpdatedAt");

                    b.HasIndex("EarthquakeId", "ModerationStatus", "Status", "Priority", "CreatedAt");

                    b.ToTable("HelpRequests");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.HelpRequestAbuseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("HelpRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HelpRequestId", "CreatedAt");

                    b.ToTable("HelpRequestAbuseReports");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.HelpRequestComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("HelpRequestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("HelpRequestId", "CreatedAt");

                    b.ToTable("HelpRequestComments");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.MissingPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aliases")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ApproximateAge")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClothingDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EarthquakeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("IdentificationDocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("IdentificationLastFour")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("IdentificationNumberHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagementCodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhysicalDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("PublicationConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SearchName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SearchName");

                    b.HasIndex("EarthquakeId", "IdentificationNumberHash")
                        .IsUnique();

                    b.HasIndex("EarthquakeId", "Status", "CreatedAt");

                    b.ToTable("MissingPeople");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.MissingPersonLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MissingPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SearchAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("MissingPersonId");

                    b.HasIndex("SearchAddress");

                    b.ToTable("MissingPersonLocations");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.MissingPersonTip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("MissingPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponderEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ResponderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResponderPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("SightedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MissingPersonId", "CreatedAt");

                    b.ToTable("MissingPersonTips");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.ReportMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DamageReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DamageReportId");

                    b.ToTable("ReportMedia");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.Shelter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ContactWhatsApp")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<Guid>("EarthquakeId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ManagementCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeratedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperatingInstructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OperationalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SearchText")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagementCodeHash")
                        .IsUnique();

                    b.HasIndex("SearchText");

                    b.HasIndex("EarthquakeId", "OperationalStatus", "UpdatedAt");

                    b.HasIndex("EarthquakeId", "ModerationStatus", "OperationalStatus", "CreatedAt");

                    b.ToTable("Shelters");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.ShelterAbuseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ShelterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId", "CreatedAt");

                    b.ToTable("ShelterAbuseReports");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.AbuseReport", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.MissingPerson", "MissingPerson")
                        .WithMany("AbuseReports")
                        .HasForeignKey("MissingPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissingPerson");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.BloodDonationCenter", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.Earthquake", "Earthquake")
                        .WithMany()
                        .HasForeignKey("EarthquakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Earthquake");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.BloodDonationCenterAbuseReport", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.BloodDonationCenter", "BloodDonationCenter")
                        .WithMany("AbuseReports")
                        .HasForeignKey("BloodDonationCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodDonationCenter");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.BloodDonationCenterComment", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.BloodDonationCenter", "BloodDonationCenter")
                        .WithMany("Comments")
                        .HasForeignKey("BloodDonationCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodDonationCenter");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.CollectionPoint", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.Earthquake", "Earthquake")
                        .WithMany()
                        .HasForeignKey("EarthquakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Earthquake");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.CollectionPointAbuseReport", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.CollectionPoint", "CollectionPoint")
                        .WithMany("AbuseReports")
                        .HasForeignKey("CollectionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionPoint");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.CollectionPointComment", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.CollectionPoint", "CollectionPoint")
                        .WithMany("Comments")
                        .HasForeignKey("CollectionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionPoint");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.DamageReport", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.Earthquake", "Earthquake")
                        .WithMany()
                        .HasForeignKey("EarthquakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Earthquake");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.HelpRequest", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.Earthquake", "Earthquake")
                        .WithMany()
                        .HasForeignKey("EarthquakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Earthquake");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.HelpRequestAbuseReport", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.HelpRequest", "HelpRequest")
                        .WithMany("AbuseReports")
                        .HasForeignKey("HelpRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HelpRequest");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.HelpRequestComment", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.HelpRequest", "HelpRequest")
                        .WithMany("Comments")
                        .HasForeignKey("HelpRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HelpRequest");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.MissingPerson", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.Earthquake", "Earthquake")
                        .WithMany()
                        .HasForeignKey("EarthquakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Earthquake");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.MissingPersonLocation", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.MissingPerson", "MissingPerson")
                        .WithMany("Locations")
                        .HasForeignKey("MissingPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissingPerson");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.MissingPersonTip", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.MissingPerson", "MissingPerson")
                        .WithMany("Tips")
                        .HasForeignKey("MissingPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissingPerson");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.ReportMedia", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.DamageReport", "DamageReport")
                        .WithMany("Media")
                        .HasForeignKey("DamageReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamageReport");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.Shelter", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.Earthquake", "Earthquake")
                        .WithMany()
                        .HasForeignKey("EarthquakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Earthquake");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.ShelterAbuseReport", b =>
                {
                    b.HasOne("QuakeReport.Data.Models.Shelter", "Shelter")
                        .WithMany("AbuseReports")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.BloodDonationCenter", b =>
                {
                    b.Navigation("AbuseReports");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.CollectionPoint", b =>
                {
                    b.Navigation("AbuseReports");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.DamageReport", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.HelpRequest", b =>
                {
                    b.Navigation("AbuseReports");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.MissingPerson", b =>
                {
                    b.Navigation("AbuseReports");

                    b.Navigation("Locations");

                    b.Navigation("Tips");
                });

            modelBuilder.Entity("QuakeReport.Data.Models.Shelter", b =>
                {
                    b.Navigation("AbuseReports");
                });
#pragma warning restore 612, 618
        }
    }
}
