<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-QuakeReport.MigrationService-639b64c3-539d-4124-aa07-94aeab4f52ab</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuakeReport.ServiceDefaults\QuakeReport.ServiceDefaults.csproj" />
    <ProjectReference Include="..\QuakeReport.Data\QuakeReport.Data.csproj" />
  </ItemGroup>
</Project>
