using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuakeReport.ApiService.Dtos;
using QuakeReport.ApiService.Earthquakes;
using QuakeReport.ApiService.MissingPeople;
using QuakeReport.Contracts.Dtos;
using QuakeReport.Contracts.Enums;
using QuakeReport.Data;
using QuakeReport.Data.Models;

namespace QuakeReport.ApiService.Controllers;

[ApiController, Route("api/blood-donation-centers")]
public class BloodDonationCentersController(QuakeReportDbContext db, ActiveEarthquakeService earthquakes, ITurnstileValidator turnstile, IConfiguration configuration) : ControllerBase
{
    private const int DefaultPageSize = 20, MaxPageSize = 100;
    [HttpGet]
    public async Task<IActionResult> List([FromQuery] string? query=null, [FromQuery] BloodDonationCenterType? centerType=null, [FromQuery] BloodDonationOperationalStatus? operationalStatus=null, [FromQuery] BloodDonationModerationStatus? moderationStatus=null, [FromQuery] BloodTypeFlags? bloodTypes=null, [FromQuery] BloodComponentFlags? components=null, [FromQuery] BloodDonationSortOption sort=BloodDonationSortOption.Newest, [FromQuery] int page=1, [FromQuery] int pageSize=DefaultPageSize, CancellationToken cancellationToken=default)
    {
        if (page<1 || pageSize<1 || pageSize>MaxPageSize || !Enum.IsDefined(sort) || (centerType is not null && !Enum.IsDefined(centerType.Value)) || (operationalStatus is not null && !Enum.IsDefined(operationalStatus.Value)) || (moderationStatus is not null && !Enum.IsDefined(moderationStatus.Value)) || !ValidBloodTypes(bloodTypes) || !ValidComponents(components)) return BadRequest("Parámetros inválidos.");
        var earthquake=await earthquakes.GetActiveEarthquakeAsync(cancellationToken); if(earthquake is null) return Ok(new PagedResponse<BloodDonationCenterSummaryResponse>([],page,pageSize,0,0));
        var centers=db.BloodDonationCenters.AsNoTracking().Where(x=>x.EarthquakeId==earthquake.Id&&x.ModerationStatus!=BloodDonationModerationStatus.Rejected);
        if(moderationStatus is not null) centers=centers.Where(x=>x.ModerationStatus==moderationStatus); if(centerType is not null) centers=centers.Where(x=>x.CenterType==centerType); if(operationalStatus is not null) centers=centers.Where(x=>x.OperationalStatus==operationalStatus); else centers=centers.Where(x=>x.OperationalStatus!=BloodDonationOperationalStatus.Closed && (x.EndsAt==null||x.EndsAt>DateTimeOffset.UtcNow)); if(bloodTypes is not null) centers=centers.Where(x=>(x.BloodTypes&bloodTypes.Value)!=0); if(components is not null) centers=centers.Where(x=>(x.Components&components.Value)!=0);
        if(!string.IsNullOrWhiteSpace(query)){var normalized=Normalize(query); centers=centers.Where(x=>x.SearchText!.Contains(normalized));}
        var total=await centers.CountAsync(cancellationToken); var ordered=sort switch{BloodDonationSortOption.RecentlyUpdated=>centers.OrderByDescending(x=>x.UpdatedAt).ThenByDescending(x=>x.Id),BloodDonationSortOption.Name=>centers.OrderBy(x=>x.Name).ThenBy(x=>x.Id),_=>centers.OrderByDescending(x=>x.CreatedAt).ThenByDescending(x=>x.Id)}; var items=await ordered.Skip((page-1)*pageSize).Take(pageSize).ToListAsync(cancellationToken); return Ok(new PagedResponse<BloodDonationCenterSummaryResponse>(items.Select(x=>x.ToSummaryResponse()).ToList(),page,pageSize,total,(int)Math.Ceiling(total/(double)pageSize)));
    }
    [HttpGet("{id:guid}")] public async Task<IActionResult> Get(Guid id,CancellationToken cancellationToken){var center=await db.BloodDonationCenters.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.ModerationStatus!=BloodDonationModerationStatus.Rejected,cancellationToken);if(center is null)return NotFound();var comments=await db.BloodDonationCenterComments.AsNoTracking().Where(x=>x.BloodDonationCenterId==id&&!x.IsHidden).OrderByDescending(x=>x.CreatedAt).Take(20).ToListAsync(cancellationToken);return Ok(center.ToResponse(comments.Select(x=>x.ToResponse()).ToList()));}
    [HttpGet("{id:guid}/comments")] public async Task<IActionResult> Comments(Guid id,[FromQuery]int page=1,[FromQuery]int pageSize=DefaultPageSize,CancellationToken cancellationToken=default){if(page<1||pageSize<1||pageSize>MaxPageSize)return BadRequest("Paginación inválida.");if(!await db.BloodDonationCenters.AnyAsync(x=>x.Id==id&&x.ModerationStatus!=BloodDonationModerationStatus.Rejected,cancellationToken))return NotFound();var comments=db.BloodDonationCenterComments.AsNoTracking().Where(x=>x.BloodDonationCenterId==id&&!x.IsHidden);var total=await comments.CountAsync(cancellationToken);var items=await comments.OrderByDescending(x=>x.CreatedAt).Skip((page-1)*pageSize).Take(pageSize).ToListAsync(cancellationToken);return Ok(new PagedResponse<BloodDonationCenterCommentResponse>(items.Select(x=>x.ToResponse()).ToList(),page,pageSize,total,(int)Math.Ceiling(total/(double)pageSize)));}
    [HttpPost] public async Task<IActionResult> Create(CreateBloodDonationCenterRequest request,CancellationToken cancellationToken){var error=Validate(request);if(error is not null)return BadRequest(error);var challenge=await turnstile.ValidateAsync(request.TurnstileToken,cancellationToken);if(challenge.ProviderUnavailable)return StatusCode(503,"El servicio de verificación no está disponible.");if(!challenge.Success)return BadRequest("La verificación humana falló.");var earthquake=await earthquakes.GetActiveEarthquakeAsync(cancellationToken);if(earthquake is null)return UnprocessableEntity("No hay un terremoto activo configurado.");var code=MissingPersonSecurity.CreateManagementCode();var center=CreateEntity(request,earthquake.Id,BloodDonationSource.Community,BloodDonationModerationStatus.Pending,code);db.BloodDonationCenters.Add(center);await db.SaveChangesAsync(cancellationToken);return CreatedAtAction(nameof(Get),new{id=center.Id},new CreateBloodDonationCenterResponse(center.ToResponse(),code));}
    [HttpPost("management/lookup")] public async Task<IActionResult> Lookup(BloodDonationCenterManagementCodeRequest request,CancellationToken cancellationToken){if(string.IsNullOrWhiteSpace(request.ManagementCode))return BadRequest("El código es obligatorio.");var hash=MissingPersonSecurity.HashManagementCode(request.ManagementCode);var center=await db.BloodDonationCenters.AsNoTracking().SingleOrDefaultAsync(x=>x.ManagementCodeHash==hash&&x.ModerationStatus!=BloodDonationModerationStatus.Rejected,cancellationToken);return center is null?NotFound():Ok(center.ToResponse());}
    [HttpPut("{id:guid}")] public async Task<IActionResult> Update(Guid id,UpdateBloodDonationCenterRequest request,[FromHeader(Name="X-Management-Code")]string? code,CancellationToken cancellationToken){var center=await db.BloodDonationCenters.SingleOrDefaultAsync(x=>x.Id==id,cancellationToken);if(center is null)return NotFound();if(!Authorize(code,center))return Unauthorized();var error=Validate(request);if(error is not null)return BadRequest(error);Apply(center,request);await db.SaveChangesAsync(cancellationToken);return Ok(center.ToResponse());}
    [HttpPatch("{id:guid}/status")] public async Task<IActionResult> Status(Guid id,UpdateBloodDonationCenterStatusRequest request,[FromHeader(Name="X-Management-Code")]string? code,CancellationToken cancellationToken){var center=await db.BloodDonationCenters.SingleOrDefaultAsync(x=>x.Id==id,cancellationToken);if(center is null)return NotFound();if(!Authorize(code,center))return Unauthorized();if(!Enum.IsDefined(request.Status))return BadRequest("Estado inválido.");center.OperationalStatus=request.Status;center.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(cancellationToken);return Ok(center.ToResponse());}
    [HttpPost("{id:guid}/comments")] public async Task<IActionResult> Comment(Guid id,CreateBloodDonationCenterCommentRequest request,CancellationToken cancellationToken){if(string.IsNullOrWhiteSpace(request.Message)||request.Message.Length>2000)return BadRequest("El comentario es obligatorio.");var challenge=await turnstile.ValidateAsync(request.TurnstileToken,cancellationToken);if(challenge.ProviderUnavailable)return StatusCode(503);if(!challenge.Success)return BadRequest("La verificación humana falló.");if(!await db.BloodDonationCenters.AnyAsync(x=>x.Id==id&&x.ModerationStatus!=BloodDonationModerationStatus.Rejected,cancellationToken))return NotFound();var comment=new BloodDonationCenterComment{Id=Guid.NewGuid(),BloodDonationCenterId=id,DisplayName=request.DisplayName?.Trim(),Message=request.Message.Trim()};db.BloodDonationCenterComments.Add(comment);await db.SaveChangesAsync(cancellationToken);return Created($"/api/blood-donation-centers/{id}/comments/{comment.Id}",comment.ToResponse());}
    [HttpPatch("{id:guid}/comments/{commentId:guid}/visibility")] public async Task<IActionResult> HideComment(Guid id,Guid commentId,[FromHeader(Name="X-Management-Code")]string? code,CancellationToken cancellationToken){var center=await db.BloodDonationCenters.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,cancellationToken);if(center is null)return NotFound();if(!Authorize(code,center))return Unauthorized();var comment=await db.BloodDonationCenterComments.SingleOrDefaultAsync(x=>x.Id==commentId&&x.BloodDonationCenterId==id,cancellationToken);if(comment is null)return NotFound();comment.IsHidden=true;await db.SaveChangesAsync(cancellationToken);return NoContent();}
    [HttpPost("{id:guid}/abuse-reports")] public async Task<IActionResult> Abuse(Guid id,BloodDonationCenterAbuseReportRequest request,CancellationToken cancellationToken){if(string.IsNullOrWhiteSpace(request.Reason))return BadRequest("El motivo es obligatorio.");var challenge=await turnstile.ValidateAsync(request.TurnstileToken,cancellationToken);if(challenge.ProviderUnavailable)return StatusCode(503);if(!challenge.Success)return BadRequest("La verificación humana falló.");if(!await db.BloodDonationCenters.AnyAsync(x=>x.Id==id,cancellationToken))return NotFound();db.BloodDonationCenterAbuseReports.Add(new BloodDonationCenterAbuseReport{Id=Guid.NewGuid(),BloodDonationCenterId=id,Reason=request.Reason.Trim(),Details=request.Details?.Trim()});await db.SaveChangesAsync(cancellationToken);return Accepted();}
    [HttpGet("moderation/pending")] public async Task<IActionResult> Pending([FromHeader(Name="X-Moderation-Service-Key")]string? key,[FromQuery]int page=1,[FromQuery]int pageSize=DefaultPageSize,CancellationToken cancellationToken=default){if(!Moderated(key)||page<1||pageSize<1||pageSize>MaxPageSize)return Unauthorized();var centers=db.BloodDonationCenters.AsNoTracking().Where(x=>x.ModerationStatus==BloodDonationModerationStatus.Pending).OrderBy(x=>x.CreatedAt);var total=await centers.CountAsync(cancellationToken);var items=await centers.Skip((page-1)*pageSize).Take(pageSize).ToListAsync(cancellationToken);return Ok(new PagedResponse<BloodDonationCenterSummaryResponse>(items.Select(x=>x.ToSummaryResponse()).ToList(),page,pageSize,total,(int)Math.Ceiling(total/(double)pageSize)));}
    [HttpPost("moderation/official")] public async Task<IActionResult> Official(CreateBloodDonationCenterRequest request,[FromHeader(Name="X-Moderation-Service-Key")]string? key,[FromHeader(Name="X-Moderator-Email")]string? moderator,CancellationToken cancellationToken){if(!Moderated(key))return Unauthorized();var error=Validate(request);if(error is not null)return BadRequest(error);var earthquake=await earthquakes.GetActiveEarthquakeAsync(cancellationToken);if(earthquake is null)return UnprocessableEntity();var center=CreateEntity(request,earthquake.Id,BloodDonationSource.Official,BloodDonationModerationStatus.Approved,null);center.ModeratedAt=DateTimeOffset.UtcNow;center.ModeratedBy=moderator?.Trim();db.BloodDonationCenters.Add(center);await db.SaveChangesAsync(cancellationToken);return CreatedAtAction(nameof(Get),new{id=center.Id},center.ToResponse());}
    [HttpPatch("moderation/{id:guid}")] public async Task<IActionResult> Moderate(Guid id,UpdateBloodDonationCenterModerationRequest request,[FromHeader(Name="X-Moderation-Service-Key")]string? key,[FromHeader(Name="X-Moderator-Email")]string? moderator,CancellationToken cancellationToken){if(!Moderated(key))return Unauthorized();if(!Enum.IsDefined(request.Status))return BadRequest();var center=await db.BloodDonationCenters.SingleOrDefaultAsync(x=>x.Id==id,cancellationToken);if(center is null)return NotFound();center.ModerationStatus=request.Status;center.ModeratedAt=DateTimeOffset.UtcNow;center.ModeratedBy=moderator?.Trim();center.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(cancellationToken);return Ok(center.ToResponse());}
    [HttpPut("moderation/{id:guid}")] public async Task<IActionResult> ModeratorUpdate(Guid id,UpdateBloodDonationCenterRequest request,[FromHeader(Name="X-Moderation-Service-Key")]string? key,CancellationToken cancellationToken){if(!Moderated(key))return Unauthorized();var center=await db.BloodDonationCenters.SingleOrDefaultAsync(x=>x.Id==id,cancellationToken);if(center is null)return NotFound();var error=Validate(request);if(error is not null)return BadRequest(error);Apply(center,request);await db.SaveChangesAsync(cancellationToken);return Ok(center.ToResponse());}
    [HttpPatch("moderation/{id:guid}/status")] public async Task<IActionResult> ModeratorStatus(Guid id,UpdateBloodDonationCenterStatusRequest request,[FromHeader(Name="X-Moderation-Service-Key")]string? key,CancellationToken cancellationToken){if(!Moderated(key))return Unauthorized();var center=await db.BloodDonationCenters.SingleOrDefaultAsync(x=>x.Id==id,cancellationToken);if(center is null)return NotFound();if(!Enum.IsDefined(request.Status))return BadRequest();center.OperationalStatus=request.Status;center.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(cancellationToken);return Ok(center.ToResponse());}
    [HttpPatch("moderation/{id:guid}/comments/{commentId:guid}/visibility")] public async Task<IActionResult> ModeratorComment(Guid id,Guid commentId,[FromHeader(Name="X-Moderation-Service-Key")]string? key,CancellationToken cancellationToken){if(!Moderated(key))return Unauthorized();var comment=await db.BloodDonationCenterComments.SingleOrDefaultAsync(x=>x.Id==commentId&&x.BloodDonationCenterId==id,cancellationToken);if(comment is null)return NotFound();comment.IsHidden=true;await db.SaveChangesAsync(cancellationToken);return NoContent();}
    private bool Moderated(string? supplied)=>!string.IsNullOrWhiteSpace(supplied)&&CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(supplied),Encoding.UTF8.GetBytes(configuration["Moderation:ApiKey"]??"__missing__")); private static bool Authorize(string? code,BloodDonationCenter center)=>!string.IsNullOrWhiteSpace(code)&&center.ManagementCodeHash is not null&&MissingPersonSecurity.Matches(code,center.ManagementCodeHash);
    private static BloodDonationCenter CreateEntity(CreateBloodDonationCenterRequest r,Guid earthquakeId,BloodDonationSource source,BloodDonationModerationStatus moderation,string? code){var c=new BloodDonationCenter{Id=Guid.NewGuid(),EarthquakeId=earthquakeId,Name=r.Name.Trim(),OrganizationName=r.OrganizationName?.Trim(),Address=r.Address.Trim(),Latitude=r.Latitude,Longitude=r.Longitude,Description=r.Description?.Trim(),OperatingInstructions=r.OperatingInstructions.Trim(),NeedsSummary=r.NeedsSummary.Trim(),PublicPhone=r.PublicPhone.Trim(),PublicWhatsApp=r.PublicWhatsApp?.Trim(),PublicEmail=r.PublicEmail?.Trim(),CenterType=r.CenterType,BloodTypes=r.BloodTypes,Components=r.Components,StartsAt=r.StartsAt,EndsAt=r.EndsAt,Source=source,ModerationStatus=moderation,ManagementCodeHash=code is null?null:MissingPersonSecurity.HashManagementCode(code)};c.SearchText=Normalize(string.Join(' ',c.Name,c.OrganizationName,c.Address,c.NeedsSummary,c.OperatingInstructions));return c;}
    private static void Apply(BloodDonationCenter c,UpdateBloodDonationCenterRequest r){c.Name=r.Name.Trim();c.OrganizationName=r.OrganizationName?.Trim();c.Address=r.Address.Trim();c.Latitude=r.Latitude;c.Longitude=r.Longitude;c.Description=r.Description?.Trim();c.OperatingInstructions=r.OperatingInstructions.Trim();c.NeedsSummary=r.NeedsSummary.Trim();c.PublicPhone=r.PublicPhone.Trim();c.PublicWhatsApp=r.PublicWhatsApp?.Trim();c.PublicEmail=r.PublicEmail?.Trim();c.CenterType=r.CenterType;c.BloodTypes=r.BloodTypes;c.Components=r.Components;c.StartsAt=r.StartsAt;c.EndsAt=r.EndsAt;c.SearchText=Normalize(string.Join(' ',c.Name,c.OrganizationName,c.Address,c.NeedsSummary,c.OperatingInstructions));c.UpdatedAt=DateTimeOffset.UtcNow;}
    private static string? Validate(CreateBloodDonationCenterRequest r)=>!r.PrivacyConsent?"Privacy consent is required.":ValidateCore(r.Name,r.Address,r.OperatingInstructions,r.NeedsSummary,r.PublicPhone,r.PublicWhatsApp,r.CenterType,r.BloodTypes,r.Components,r.StartsAt,r.EndsAt); private static string? Validate(UpdateBloodDonationCenterRequest r)=>ValidateCore(r.Name,r.Address,r.OperatingInstructions,r.NeedsSummary,r.PublicPhone,r.PublicWhatsApp,r.CenterType,r.BloodTypes,r.Components,r.StartsAt,r.EndsAt);
    private static string? ValidateCore(string name,string address,string instructions,string needs,string phone,string? whatsapp,BloodDonationCenterType type,BloodTypeFlags types,BloodComponentFlags components,DateTimeOffset? starts,DateTimeOffset? ends){if(string.IsNullOrWhiteSpace(name)||name.Length>200)return"El nombre es obligatorio.";if(string.IsNullOrWhiteSpace(address)||address.Length>400)return"La dirección es obligatoria.";if(string.IsNullOrWhiteSpace(instructions)||instructions.Length>2500)return"Las instrucciones son obligatorias.";if(string.IsNullOrWhiteSpace(needs)||needs.Length>2000)return"El resumen de necesidades es obligatorio.";if(string.IsNullOrWhiteSpace(phone)&&string.IsNullOrWhiteSpace(whatsapp))return"Indica un teléfono o WhatsApp público.";if(!Enum.IsDefined(type)||!ValidBloodTypes(types)||!ValidComponents(components))return"Selecciona tipos de sangre y componentes válidos.";if(type==BloodDonationCenterType.TemporaryCampaign&&(starts is null||ends is null))return"Las campañas requieren fecha de inicio y fin.";if(starts is not null&&ends is not null&&ends<starts)return"La fecha final no puede ser anterior a la inicial.";return null;}
    private static bool ValidBloodTypes(BloodTypeFlags? value)=>value is null||value.Value!=BloodTypeFlags.None&&(value.Value&~(BloodTypeFlags.APositive|BloodTypeFlags.ANegative|BloodTypeFlags.BPositive|BloodTypeFlags.BNegative|BloodTypeFlags.ABPositive|BloodTypeFlags.ABNegative|BloodTypeFlags.OPositive|BloodTypeFlags.ONegative|BloodTypeFlags.Unknown))==0; private static bool ValidComponents(BloodComponentFlags? value)=>value is null||value.Value!=BloodComponentFlags.None&&(value.Value&~(BloodComponentFlags.WholeBlood|BloodComponentFlags.RedBloodCells|BloodComponentFlags.Plasma|BloodComponentFlags.Platelets|BloodComponentFlags.Unknown))==0; private static string Normalize(string? value)=>string.IsNullOrWhiteSpace(value)?string.Empty:new(value.Normalize(System.Text.NormalizationForm.FormD).Where(c=>CharUnicodeInfo.GetUnicodeCategory(c)!=UnicodeCategory.NonSpacingMark&&(char.IsLetterOrDigit(c)||char.IsWhiteSpace(c))).Select(char.ToUpperInvariant).ToArray());
}
